name: rifugio-monitor
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.11
  
  # Core dependencies
  - requests>=2.31.0
  - pyyaml>=6.0
  - numpy>=1.24.0
  
  # PDF processing
  - pip
  - pip:
    - PyPDF2>=3.0.1
    - pdfplumber>=0.9.0
    
  # Image processing
  - pillow>=10.0.0
  - pdf2image>=1.16.3
  
  # OCR support (optional)
  - tesseract>=4.1.0
  - pip:
    - pytesseract>=0.3.10
  
  # Development tools
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - pytest-mock>=3.11.1
  - black>=23.7.0
  - flake8>=6.0.0
  - isort>=5.12.0
  - mypy>=1.5.0
  - pre-commit>=3.3.3
  - ipython>=8.14.0
  - jupyter>=1.0.0
  
  # Additional dev dependencies via pip
  - pip:
    - freezegun>=1.2.2
    - responses>=0.23.1
    - factory-boy>=3.3.0
    - sphinx>=7.1.0
    - sphinx-rtd-theme>=1.3.0