# Rifugio Availability Monitor Configuration

# PDF Settings
pdf:
  url: "https://www.rifugiopiandicengia.it/CustomerData/764/Files/Documents/verfuegbarkeiten.pdf"
  download_timeout: 30
  
# Monitoring Settings  
monitoring:
  target_dates:
    - "2025-09-12"
    - "2025-09-13"
    - "2025-09-14"
    - "2025-09-15"
    - "2025-09-16"
    - "2025-09-17"
    - "2025-09-18"
    - "2025-09-19"
    - "2025-09-20"
    - "2025-09-21"
  
  schedule:
    frequency: "2hours"  # every 2 hours during business hours
    timezone: "Europe/Rome"
  
# Analysis Methods Configuration
analysis:
  methods:
    text_extraction:
      enabled: true
      priority: 1
    image_analysis: 
      enabled: true
      priority: 2
      dpi: 200
    ocr_analysis:
      enabled: true
      priority: 3
      dpi: 300
      languages: ["deu", "eng"]
  
  color_thresholds:
    available: 
      - [0, 255, 0]      # Pure green
      - [50, 255, 50]    # Light green
    booked:
      - [255, 0, 0]      # Pure red  
      - [255, 50, 50]    # Light red
    day_use:
      - [255, 255, 0]    # Pure yellow
      - [255, 255, 100]  # Light yellow
    closed:
      - [255, 255, 255]  # White
      - [240, 240, 240]  # Off-white
  
# Email Notification Settings
email:
  smtp:
    server: "smtp.gmail.com"
    port: 587
    use_tls: true
  
  templates:
    change_detected:
      subject: "🏔️ Rifugio Calendar Updated!"
      include_availability: true
      include_technical_details: true
    
    error:
      subject: "⚠️ Rifugio Monitor Error"
      include_logs: false
  
# Storage Settings
storage:
  hash_file: "data/last_hash.txt"
  availability_file: "data/availability.json"
  log_file: "monitor.log"
  
# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(levelname)s - %(message)s"
  max_file_size: "10MB"
  backup_count: 5