name: Check Rifugio Availability

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-availability:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install pdfplumber numpy requests
    
    - name: Check availability
      run: python check_availability.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}